// ! test kommentar
// # test kommentar
// * test kommentar
// todo test kommentar
// - test kommentar
// ? test kommentar
// : test kommentar
// // test kommentar
// + test kommentar
// & test kommentar
// $ test kommentar
// > test kommentar
// info test kommentar
